### ISSUE TITLE
请问能否给个数据集的下载地址？

### ISSUE THREAD

**Issue by JohanWill** [brooklyn1900/SPCNet#2]

**Comment by JohanWill** [comment]
我手上只有icdar2017的total-text数据集，里面包含很多弯曲文本（我想用SPCNet识别弯曲文本），但是这些图片的Annotations是“x: [[206 251 386 542 620 646 550 358 189 140]], y: [[ 633  811  931  946  926  976 1009  989  845  629]], ornt: [u'c'], transcriptions: [u'PETROSAINS']”这种格式的。请问一下大佬这种格式要怎么转换..能否直接输到网络里面呢？

**Comment by brooklyn1900** [comment]
数据集在data目录下
